require(ggplot2)
summary(mpg)
a<-ggplot(mpg,aes(hwy))
a+geom_area(stat="bin")
a+geom_density(kernel = "gaussian")
a+geom_freqpoly()
a+geom_histogram()
summary(economics)
d<-ggplot(economics,aes(date, unemploy))
d+geom_ribbon(aes(ymin=unemploy-900, ymax=unemploy+900))
f<-ggplot(mpg,aes(cty,hwy))
f+geom_jitter()
f+geom_point()
reg<-lm(mpg$hwy~mpg$cty)
f+geom_jitter()
f+geom_quantile()
f+geom_jitter()+geom_quantile()
f+geom_smooth()

qplot(mpg$cty,mpg$hwy,size=mpg$cyl, geom = "jitter", col="red")
qplot(mpg$cty,mpg$hwy,color=mpg$cyl, geom = "jitter")
